// this file needs to use module.s as it is used both by react and electron
// the original file is located in src/shared and is duplicated in public/shared

const FLAG_GETTING_DATASET = 'FLAG_GETTING_DATASET';
const GET_DATASET_SUCCESS = 'GET_DATASET_SUCCESS';
const GET_DATASETS_SUCCESS = 'GET_DATASETS_SUCCESS';
const FLAG_GETTING_DATASETS = 'FLAG_GETTING_DATASETS';
const LOAD_DATASET_SUCCESS = 'LOAD_DATASET_SUCCESS';
const LOAD_DATASET_ERROR = 'LOAD_DATASET_ERROR';
const FLAG_LOADING_DATASET = 'FLAG_LOADING_DATASET';
const FLAG_GETTING_DATABASE = 'FLAG_GETTING_DATABASE';
const GET_DATABASE_SUCCESS = 'GET_DATABASE_SUCCESS';
const GET_DATABASE_ERROR = 'GET_DATABASE_ERROR';
const FLAG_SETTING_SAMPLE_DATABASE = 'FLAG_SETTING_SAMPLE_DATABASE';
const SET_SAMPLE_DATABASE_SUCCESS = 'SET_SAMPLE_DATABASE_SUCCESS';
const SET_SAMPLE_DATABASE_ERROR = 'SET_SAMPLE_DATABASE_ERROR';
const FLAG_SETTING_DATABASE = 'FLAG_SETTING_DATABASE';
const GET_DATASET_ERROR = 'GET_DATASET_ERROR';
const GET_DATASETS_ERROR = 'GET_DATASETS_ERROR';
const SET_DATABASE_SUCCESS = 'SET_DATABASE_SUCCESS';
const SET_DATABASE_ERROR = 'SET_DATABASE_ERROR';
const EXECUTE_PYTHON_ALGORITHM_ERROR = 'EXECUTE_PYTHON_ALGORITHM_ERROR';
const EXECUTE_PYTHON_ALGORITHM_SUCCESS = 'EXECUTE_PYTHON_ALGORITHM_SUCCESS';
const FLAG_DELETING_DATASET = 'FLAG_DELETING_DATASET';
const DELETE_DATASET_SUCCESS = 'DELETE_DATASET_SUCCESS';
const DELETE_DATASET_ERROR = 'DELETE_DATASET_ERROR';
const DELETE_ALGORITHM_ERROR = 'DELETE_ALGORITHM_ERROR';
const GET_ALGORITHMS_SUCCESS = 'GET_ALGORITHMS_SUCCESS';
const FLAG_GETTING_ALGORITHMS = 'FLAG_GETTING_ALGORITHMS';
const DELETE_ALGORITHM_SUCCESS = 'DELETE_ALGORITHM_SUCCESS';
const FLAG_DELETING_ALGORITHM = 'FLAG_DELETING_ALGORITHM';
const FLAG_GETTING_RESULT = 'FLAG_GETTING_RESULT';
const GET_RESULT_SUCCESS = 'GET_RESULT_SUCCESS';
const GET_RESULT_ERROR = 'GET_RESULT_ERROR';
const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
const FLAG_GETTING_RESULTS = 'FLAG_GETTING_RESULTS';
const FLAG_DELETING_RESULT = 'FLAG_DELETING_RESULT';
const DELETE_RESULT_SUCCESS = 'DELETE_RESULT_SUCCESS';
const DELETE_RESULT_ERROR = 'DELETE_RESULT_ERROR';
const FLAG_GETTING_LANGUAGE = 'FLAG_GETTING_LANGUAGE';
const FLAG_SETTING_LANGUAGE = 'FLAG_SETTING_LANGUAGE';
const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS';
const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS';
const GET_LANGUAGE_ERROR = 'GET_LANGUAGE_ERROR';
const GET_RESULTS_ERROR = 'GET_RESULTS_ERROR';
const FLAG_EXECUTING_ALGORITHM = 'FLAG_EXECUTING_ALGORITHM';
const CHECK_PYTHON_INSTALLATION_SUCCESS = 'CHECK_PYTHON_INSTALLATION_SUCCESS';
const CHECK_PYTHON_INSTALLATION_ERROR = 'CHECK_PYTHON_INSTALLATION_ERROR';
const FLAG_CHECKING_PYTHON_VERSION = 'FLAG_CHECKING_PYTHON_VERSION';
const GET_ALGORITHMS_ERROR = 'GET_ALGORITHMS_ERROR';
const GET_ALGORITHM_ERROR = 'GET_ALGORITHM_ERROR';
const FLAG_EXPORTING_DATASET = 'FLAG_EXPORTING_DATASET';
const EXPORT_DATASET_SUCCESS = 'EXPORT_DATASET_SUCCESS';
const EXPORT_DATASET_ERROR = 'EXPORT_DATASET_ERROR';
const FLAG_EXPORTING_RESULT = 'FLAG_EXPORTING_RESULT';
const EXPORT_RESULT_SUCCESS = 'EXPORT_RESULT_SUCCESS';
const EXPORT_RESULT_ERROR = 'EXPORT_RESULT_ERROR';
const SET_DATASET_FILE_SUCCESS = 'SET_DATASET_FILE_SUCCESS';
const SET_DATASET_FILE_ERROR = 'SET_DATASET_FILE_ERROR';
const FLAG_SETTING_DATASET_FILE = 'FLAG_SETTING_DATASET_FILE';
const GET_ALGORITHM_SUCCESS = 'GET_ALGORITHM_SUCCESS';
const FLAG_GETTING_ALGORITHM = 'FLAG_GETTING_ALGORITHM';
const FLAG_SAVING_ALGORITHM = 'FLAG_SAVING_ALGORITHM';
const SAVE_ALGORITHM_SUCCESS = 'SAVE_ALGORITHM_SUCCESS';
const SAVE_ALGORITHM_ERROR = 'SAVE_ALGORITHM_ERROR';
const FLAG_ADDING_ALGORITHM = 'FLAG_ADDING_ALGORITHM';
const ADD_ALGORITHM_SUCCESS = 'ADD_ALGORITHM_SUCCESS';
const ADD_ALGORITHM_ERROR = 'ADD_ALGORITHM_ERROR';
const CLEAR_ALGORITHM = 'CLEAR_ALGORITHM';

module.exports = {
  FLAG_GETTING_DATABASE,
  GET_DATABASE_SUCCESS,
  GET_DATABASE_ERROR,
  FLAG_SETTING_SAMPLE_DATABASE,
  SET_SAMPLE_DATABASE_SUCCESS,
  SET_SAMPLE_DATABASE_ERROR,
  FLAG_SETTING_DATABASE,
  FLAG_GETTING_DATASET,
  GET_DATASET_SUCCESS,
  GET_DATASETS_SUCCESS,
  FLAG_GETTING_DATASETS,
  LOAD_DATASET_ERROR,
  LOAD_DATASET_SUCCESS,
  FLAG_LOADING_DATASET,
  GET_DATASET_ERROR,
  GET_DATASETS_ERROR,
  SET_DATABASE_SUCCESS,
  SET_DATABASE_ERROR,
  EXECUTE_PYTHON_ALGORITHM_ERROR,
  EXECUTE_PYTHON_ALGORITHM_SUCCESS,
  FLAG_DELETING_DATASET,
  DELETE_DATASET_SUCCESS,
  DELETE_DATASET_ERROR,
  DELETE_ALGORITHM_ERROR,
  GET_ALGORITHMS_SUCCESS,
  FLAG_GETTING_ALGORITHMS,
  DELETE_ALGORITHM_SUCCESS,
  FLAG_DELETING_ALGORITHM,
  FLAG_GETTING_RESULT,
  FLAG_GETTING_RESULTS,
  GET_RESULT_SUCCESS,
  GET_RESULTS_SUCCESS,
  FLAG_DELETING_RESULT,
  DELETE_RESULT_SUCCESS,
  DELETE_RESULT_ERROR,
  FLAG_GETTING_LANGUAGE,
  FLAG_SETTING_LANGUAGE,
  GET_LANGUAGE_SUCCESS,
  GET_LANGUAGE_ERROR,
  SET_LANGUAGE_SUCCESS,
  GET_RESULT_ERROR,
  GET_RESULTS_ERROR,
  FLAG_EXECUTING_ALGORITHM,
  CHECK_PYTHON_INSTALLATION_SUCCESS,
  CHECK_PYTHON_INSTALLATION_ERROR,
  FLAG_CHECKING_PYTHON_VERSION,
  GET_ALGORITHMS_ERROR,
  GET_ALGORITHM_ERROR,
  FLAG_EXPORTING_DATASET,
  EXPORT_DATASET_SUCCESS,
  EXPORT_DATASET_ERROR,
  FLAG_EXPORTING_RESULT,
  EXPORT_RESULT_SUCCESS,
  EXPORT_RESULT_ERROR,
  SET_DATASET_FILE_SUCCESS,
  SET_DATASET_FILE_ERROR,
  FLAG_SETTING_DATASET_FILE,
  GET_ALGORITHM_SUCCESS,
  FLAG_GETTING_ALGORITHM,
  FLAG_SAVING_ALGORITHM,
  SAVE_ALGORITHM_SUCCESS,
  SAVE_ALGORITHM_ERROR,
  FLAG_ADDING_ALGORITHM,
  ADD_ALGORITHM_SUCCESS,
  ADD_ALGORITHM_ERROR,
  CLEAR_ALGORITHM,
};
