export const GET_ALGORITHMS_SUCCESS = 'GET_ALGORITHMS_SUCCESS';
export const FLAG_GETTING_ALGORITHMS = 'FLAG_GETTING_ALGORITHMS';
export const DELETE_ALGORITHM_SUCCESS = 'DELETE_ALGORITHM_SUCCESS';
export const FLAG_DELETING_ALGORITHM = 'FLAG_DELETING_ALGORITHM';
