export const FLAG_GETTING_DATABASE = 'FLAG_GETTING_DATABASE';
export const GET_DATABASE_SUCCEEDED = 'GET_DATABASE_SUCCEEDED';
export const FLAG_SETTING_SAMPLE_DATABASE = 'FLAG_SETTING_SAMPLE_DATABASE';
export const SET_SAMPLE_DATABASE_SUCCEEDED = 'SET_SAMPLE_DATABASE_SUCCEEDED';
export const SET_DATABASE_SUCCEEDED = 'SET_DATABASE_SUCCEEDED';
export const FLAG_SETTING_DATABASE = 'FLAG_SETTING_DATABASE';
