export const FLAG_GETTING_LANGUAGE = 'FLAG_GETTING_LANGUAGE';
export const FLAG_SETTING_LANGUAGE = 'FLAG_SETTING_LANGUAGE';
export const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS';
export const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS';
