export const FLAG_GETTING_LANGUAGE = 'FLAG_GETTING_LANGUAGE';
export const FLAG_SETTING_LANGUAGE = 'FLAG_SETTING_LANGUAGE';
export const GET_LANGUAGE_SUCCEEDED = 'GET_LANGUAGE_SUCCEEDED';
export const SET_LANGUAGE_SUCCEEDED = 'SET_LANGUAGE_SUCCEEDED';
